#! /bin/sh

echo "Hi from `basename $0`"

EXCELDIR=`pwd`
echo $EXCELDIR
CONFIGDIR="$EXCELDIR/.."
THRIFTDIR="$CONFIGDIR/Thrift"
UTILSDIR="$CONFIGDIR/Utils"
PROJECTDIR="$CONFIGDIR/.."
DATADIR=PROJECTDIR
CONVERT="$UTILSDIR/convert.py"

ls "$EXCELDIR"

python3 $CONVERT
