/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Config_constants.h"

namespace Yoga { namespace Config {

const ConfigConstants g_Config_constants;

ConfigConstants::ConfigConstants() {
}

}} // namespace

