
name: Update Config

on: [push]

permissions:
  contents: read

jobs:
  BuildConfig:

    # thrift is too difficult to build on the other platforms
    runs-on: windows-latest #ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    env:
      CONFIG_API_TOKEN: ${{ secrets.CONFIG_API_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Generate thrift source
      working-directory: ./Config/Thrift
      run: |
        ../../thrift-0.20.0.exe --gen py Config.thrift

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create new config and get config id - Windows
      if: runner.os == 'Windows'
      run: |
        $response = Invoke-Expression "curl -X POST https://config.allknownmetalbands.com/api/configs -H 'Content-Type: application/json' -d '{"gitHash": "db1b58efcf8c0366995c9a28afcbcae9c2727ed2", "branchName": "main", "projectName": "Power Yoga Center"}' -H 'Authorization: Bearer ${{ secrets.CONFIG_API_KEY }}'"
        Write-Output $response
        $configId = ($response | Select-String -Pattern '"id":"([^"]+)"' -AllMatches).Matches.Groups[1].Value
        Write-Output "Config ID: $configId"

    - name: Create new config and get config id - non-Windows (untested)
      if: runner.os != 'Windows'
      run: |
        RESPONSE=$(curl -X POST https://config.allknownmetalbands.com/api/configs -H "Content-Type: application/json" -d '{"gitHash": "db1b58efcf8c0366995c9a28afcbcae9c2727ed2", "branchName": "main", "projectName": "Power Yoga Center"}' -H "Authorization: Bearer ${{ secrets.CONFIG_API_KEY }}")
        echo "$RESPONSE"
        CONFIG_ID=$(echo "$RESPONSE" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p')
        echo "Config ID: ${CONFIG_ID}"
          
    - name: Update config status to BUILDING
      run: |
        response = curl -X POST https://config.allknownmetalbands.com/api/configs/update-status -H "Content-Type: application/json" \
          -d '{"id": "${CONFIG_ID}", "status": "BUILDING"}' 
          -H "Authorization: Bearer ${{ secrets.CONFIG_API_KEY }}"
  
    - name: Build config
      working-directory: ./Config/Excel
      run: |
        dir
        ./convert.sh
        ./mutate.sh
        cp ../../config.bin "../../config_${CONFIG_ID}.bin"
        echo pwd
        pwd
        echo ls
        ls
        echo ls ../..
        ls ../..

    - name: Calculate checksum
      working-directory: ./Config/Excel
      run: |
        CHECKSUM=$(md5sum "../../config_${CONFIG_ID}.bin"
        #  > "../../config_${{ steps.confignum.outputs.result }}.md5")
        echo "CHECKSUM is $CHECKSUM"

    - name: "install aws cli"
      uses: ohthepain/action-install-aws-cli@v0.14

    - name: test aws cli
      run: aws s3 ls
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'

    - name: Upload S3
      uses: hkusu/s3-upload-action@v2
      id: upload # specify some ID for use in subsequent steps
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'
        aws-bucket: 'yoga.config'
        file-path: "./config_${CONFIG_ID}.bin"
        destination-dir: '/'
        output-file-url: 'true' # specify output
    - name: Show Config URL
      run: echo '${{ steps.upload.outputs.file-url }}' # use output

    - name: Complete the config
      run: |
        response = curl -X POST https://config.allknownmetalbands.com/api/configs/complete -H "Content-Type: application/json" \
          -d '{"id": "${CONFIG_ID}", "checksumMd5": "${CHECKSUM}", "downloadUrl": "${{ steps.upload.outputs.file-url }}"}' 
          -H "Authorization: Bearer ${{ secrets.CONFIG_API_KEY }}"
  
      
