
name: Update Config

on: [push]

permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        cd Config/Thrift
        thrift --gen py Config.thrift
        pip install -r requirements.txt
        cd Config/Excel
        ./convert.sh
        ./mutate.sh
