
name: Update Config

on: [push]

permissions:
  contents: read

jobs:
  BuildConfig:

    # thrift is too difficult to build on the other platforms
    runs-on: windows-latest #ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    env:
      CONFIG_API_TOKEN: ${{ secrets.CONFIG_API_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    # - name: Install thrift
    #   run: |
    #     sudo apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
    #     echo start part 2
    #     curl -O https://dlcdn.apache.org/thrift/0.20.0/thrift-0.20.0.tar.gz
    #     echo start part 3
    #     ls -l thrift-0.20.0.tar.gz
    #     echo start part 4
    #     tar -xvf thrift-0.20.0.tar.gz
    #     echo start part 5
    #     cd thrift-0.20.0
    #     ./bootstrap.sh
    #     echo start part 6
    #     ./configure --without-java --without-kotlin --without-erlang --without-nodejs --without-nodets --without-lua --without-perl --without-dart --without-haskell --without-swift --without-ruby --without-go --enable-tutorial=no --enable-coverage=no --disable-dependency-tracking
    #     echo start part 7
    #     sudo make

    - name: Increment config number
      uses: ohthepain/global-build-numbers@v0.16
      id: confignum
      with:
        DYNAMO_TABLE_NAME: 'build-numbers'
        DYNAMO_PARTITION_KEY: 'product-id'
        PRODUCT_ID: 'yoga-config'
        OPERATION: 'increment'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'

    - name: Echo config number
      run: echo We don't use these config numbers anymore ${{ steps.confignum.outputs.result }}

    - name: Generate thrift source
      working-directory: ./Config/Thrift
      run: |
        ../../thrift-0.20.0.exe --gen py Config.thrift
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create new config and get config id
      run: |
        response = curl -X POST https://config.allknownmetalbands.com/api/configs -H "Content-Type: application/json" \
          -d '{"gitHash": "db1b58efcf8c0366995c9a28afcbcae9c2727ed2", "branchName": "main", "projectName": "Power Yoga Center"}' 
          -H "Authorization: Bearer ${{ secrets.CONFIG_API_KEY }}"
        config_id=$(echo $response | jq -r '.id')
        echo "Config ID: $config_id"

    - name: Update config status to BUILDING
      run: |
        response = curl -X POST https://config.allknownmetalbands.com/api/configs/update-status -H "Content-Type: application/json" \
          -d '{"id": "$config_id", "status": "BUILDING"}' 
          -H "Authorization: Bearer ${{ secrets.CONFIG_API_KEY }}"
  
    - name: Build config
      working-directory: ./Config/Excel
      run: |
        dir
        ./convert.sh
        ./mutate.sh
        cp ../../config.bin "../../config_$config_id.bin"
        echo pwd
        pwd
        echo ls
        ls
        echo ls ../..
        ls ../..

    - name: Calculate checksum
      working-directory: ./Config/Excel
      run: |
        checksum = md5sum "../../config_${{ steps.confignum.outputs.result }}.bin" > "../../config_${{ steps.confignum.outputs.result }}.md5"
        echo "checksum is $checksum"

    - name: "install aws cli"
      uses: ohthepain/action-install-aws-cli@v0.14
      # All commands after this point have access to the AWS CLI
    - run: aws s3 ls
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'

    - name: Upload S3
      uses: hkusu/s3-upload-action@v2
      id: upload # specify some ID for use in subsequent steps
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'
        aws-bucket: 'yoga.config'
        file-path: "./config_${{ steps.confignum.outputs.result }}.bin"
        destination-dir: '/'
        output-file-url: 'true' # specify output
    - name: Show Config URL
      run: echo '${{ steps.upload.outputs.file-url }}' # use output

    - name: Complete the config
      run: |
        response = curl -X POST https://config.allknownmetalbands.com/api/configs/complete -H "Content-Type: application/json" \
          -d '{"id": "$config_id", "checksumMd5": "$checksum", "downloadUrl": "${{ steps.upload.outputs.file-url }}"}' 
          -H "Authorization: Bearer ${{ secrets.CONFIG_API_KEY }}"
  
      
